version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./pos_delivery:/mnt/extra-addons/pos_delivery
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: -- --addons-path=/mnt/extra-addons,/mnt/enterprise-addons
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
